version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5073:5073" # Map container port 80 to host port 5000
      - "7299:7299" # Map container port 443 to host port 5001
    environment:
      - MongoDb__DatabaseName=mongo
      - MongoDb__ConnectionString=mongodb://mongo:mongo@mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo