name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx"

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/productapi:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/productapi:latest

    - name: Clone deployment repo
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone https://${{ secrets.MANIFEST_REPO_TOKEN }}@${{ secrets.MANIFEST_REPO_URL }} manifest-repo
        cp -r k8s/* manifest-repo/
        cd manifest-repo
        git checkout -b update-k8s-manifests
        git add .
        git commit -m "Update k8s manifests for latest deploy"
        git push origin update-k8s-manifests
      env:
        GIT_TERMINAL_PROMPT: 0

    - name: Create PR in manifest repo
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "update-k8s-manifests"
        destination_branch: "main"
        github_token: ${{ secrets.MANIFEST_REPO_TOKEN }}
        pr_title: "Update K8s manifests for latest deploy"
        pr_body: "Auto-generated by CI/CD pipeline"
        pr_reviewer: "diegopereira-ti" # optional
